import {initializeApp} from "firebase-admin/app";

initializeApp();

export {createDeviceRequest} from "./device/createDeviceRequest";
export {createDeviceRequestInternal} from "./device/createDeviceRequestInternal";
export {changeStatus} from "./device/changeStatus";
export {assignVolunteer} from "./device/assignVolunteer";
export { register, checkRegistration, completeRegistration, registerWithIntegratedAuth, doLogin } from "./auth/register";
export { setPassword } from "./auth/setPassword";
export { activateVolunteers, deactivateVolunteers } from "./volunteer/volunteerState";
export { updateVolunteerProfile } from "./volunteer/updateVolunteerProfile";
export { addPrinter } from "./volunteer/addPrinter";
export { inviteVolunteer } from "./volunteer/invite";
export { acceptVolunteerConsents } from "./volunteer/acceptVolunteerConsents";
export { setUserRole } from "./volunteer/setUserRole";
export { listVolunteerAdminData } from "./volunteer/listVolunteerAdminData";
export { createShipmentRequest, approveShipmentRequest, deleteShipmentRequest } from "./shipments/shipmentRequests";
export { saveGlobalMessage } from "./device/saveGlobalMessage";
export { updateChecklist } from "./organizer/updateChecklist";
export { createChecklist } from "./organizer/createChecklist";
export { createChecklistFromTemplate } from "./organizer/createChecklistFromTemplate";
export { cloneChecklist } from "./organizer/cloneChecklist";
export { listTemplates } from "./organizer/listTemplates";
export { listMyChecklistItems } from "./organizer/listMyChecklistItems";
export { createDeviceChecklistTemplate } from "./device-requests/createChecklistTemplate";
export { updateDeviceChecklistTemplate } from "./device-requests/updateChecklistTemplate";
export { deleteDeviceChecklistTemplate } from "./device-requests/deleteChecklistTemplate";
export { createDeviceRequestChecklist } from "./device-requests/createDeviceRequestChecklist";
export { cloneDeviceRequestChecklist } from "./device-requests/cloneDeviceRequestChecklist";
export { deleteChecklist } from "./organizer/deleteChecklist";
export { getDeviceRequestChecklist } from "./device-requests/getDeviceRequestChecklist";
export { getDeviceRequestChecklistCompleteness } from "./device-requests/getDeviceRequestChecklistCompleteness";
export { addDeviceRequestChecklistItem } from "./device-requests/addDeviceRequestChecklistItem";
export { updateDeviceRequestChecklistItem } from "./device-requests/updateDeviceRequestChecklistItem";
export { removeDeviceRequestChecklistItem } from "./device-requests/removeDeviceRequestChecklistItem";
export { createChecklistShareLink } from "./device-requests/createChecklistShareLink";
export { getChecklistShareStatus } from "./device-requests/getChecklistShareStatus";

console.log("REGISTER BUILD SUCCESSFUL - " + new Date().toISOString());
